server:
  port: 8000
# Spring
spring:
  rabbitmq:
    port: 5672
    host: 192.168.99.100
    username: guest
    password: guest
  application:
    name: biz-publisher
  # 服务器邮箱
  mail:
    host: smtp.qq.com
    username: 1009710828@qq.com
    password: lxrcpmnozinfbeei
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    default-encoding: UTF-8
    test-connection: true

# MyBatis
mybatis:
  mapper-locations: classpath:featureselection/research/web/mybatisMapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# Logback
logging:
  path: '/logs'
#  level:
#    featureSelection.research.web.mybatisMapper: debug