# Spring
spring:
  # 服务器邮箱
  mail: 
    host: smtp.qq.com
    username: xxxxxx@xxx.com
    password: xxxxxxxxxxxxxx
    properties:
      mail:
        smtp: 
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
# MyBatis
mybatis: 
  mapper-locations: classpath:featureselection/research/web/mybatisMapper/*.xml
# Logback    
logging:
  path: '/logs'
