server:
  port: 8000
# Spring
spring:
  application:
    name: biz-publisher
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  # 服务器邮箱
  mail:
    host: smtp.qq.com
    username: xxxxxx@xxx.com
    password: xxxxxxxxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# MyBatis
mybatis:
  mapper-locations: classpath:featureselection/research/web/mybatisMapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# Logback
logging:
  path: '/logs'
  level:
    featureSelection.research.web.mybatisMapper: debug