server:
  port: 8000
# Spring
spring:
  application:
    name: biz-publisher
  # 服务器邮箱
  rabbitmq:
    host: localhost
    port: 5672
    username: featureselectionreciver
    password: reciver
    localResultReciverExchange: resultReciverExchange
    localDemoResultReciverRoutingkey: demoResultReciverRoutingkey
    localExecutionResultReciverRoutingkey: executionResultReciverRoutingkey
  mail:
    host: smtp.qq.com
    username: 1009710828@qq.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    default-encoding: UTF-8
    test-connection: true

# MyBatis
mybatis:
  mapper-locations: classpath:featureselection/research/web/mybatisMapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# Logback
logging:
  path: '/logs'
  level:
    featureSelection.research.web.mybatisMapper: debug

appconfigs:
  MaxExceptionNumberPerMinute4Exit: 100
  ReciverExceptionNoticeEmail:
